### PR TITLE
Fix country name labels

### PR DESCRIPTION
**Pull request by rtaph**
This PR introduces a data dictionary containing the country name mappings between Altair, the obesity dataset, and the World Bank dataset. These are used to fix a join bug in the data cleaning stage.

### CODE REVIEW

**Review by jraza19 — COMMENTED** [review]
Great work @rtaph

**Comment by rtaph** [comment]
image

The other countries are back! But maybe at some stage we want to consider what to do about South Sudan. I'm also noticing there still is a join issue with Côte d'Ivoire.

**Comment by rtaph** [comment]
Altair geosjon objects that don't exist in our data:

- 'American Samoa',
-  'Andorra',
-  'Bermuda',
-  'British Virgin Islands',
-  'Cayman Islands',
-  'Dominica',
-  'Faroe Islands',
-  'Gibraltar',
-  'Greenland',
-  'Isle of Man',
-  'Kosovo',
-  'Liechtenstein',
-  'Marshall Islands',
-  'Monaco',
-  'Nauru',
-  'Northern Mariana Islands',
-  'Not classified',
-  'Palau',
-  'San Marino',
-  'Sint Maarten (Dutch part)',
-  'St. Kitts and Nevis',
-  'St. Martin (French part)',
-  'Turks and Caicos Islands',
-  'Tuvalu'

These are small jurisdictions anyway, so would not be visible.

**Review by tanmaysharma19 — APPROVED** [review]
LGTM!

**Pull request merged**
